name: CI

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  linting: 
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ['3.9', '3.10']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install flake 8 
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake 8
        run: |
          flake8 app.py

